name: Security Check

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Security vulnerabilities scan
        uses: pypa/gh-action-pip-audit@v1.0.8 